// src/domain/types.ts — Pure TypeScript interfaces (no runtime dependencies except Zod inferred types)

export interface ExpectedMetrics {
  mvpMonthlyUsers: number;
  scaleMonthlyUsers: number;
  peakConcurrentConnections: number;
}

export interface Agent1Output {
  projectName: string;
  productVision: string;
  targetAudience: string;
  valueProposition: string;
  mvpFeatures: string[];
  expectedMetrics: ExpectedMetrics;
}

export interface SolidBoundary {
  principle: string;
  rule: string;
  layer: string;
}

export interface SecurityGuard {
  name: string;
  description: string;
  enforcement: string;
}

export interface TechSteering {
  stack: string[];
  architecturePattern: "Clean" | "Hexagonal";
  solidBoundaries: SolidBoundary[];
  securityGuards: SecurityGuard[];
}

export interface EntityProperty {
  name: string;
  type: string;
  required: boolean;
}

export interface DomainEntity {
  name: string;
  properties: EntityProperty[];
  relationships: string[];
}

export interface IamPolicy {
  service: string;
  actions: string[];
  resource: string;
  effect: "Allow" | "Deny";
}

export interface ServiceCost {
  service: string;
  monthlyCostUsd: number;
}

export interface CostProjection {
  mvpMonthlyCostUsd: ServiceCost[];
  scaleMonthlyCostUsd: ServiceCost[];
}

export interface DesignOutput {
  domainEntities: DomainEntity[];
  mermaidDiagram: string;
  iamPolicySummary: IamPolicy[];
  awsCostProjection: CostProjection;
}

export interface TaskItem {
  id: string;
  title: string;
  description: string;
  dependencies: string[];
}

export interface Agent2Output {
  techSteering: TechSteering;
  requirements: string;
  design: DesignOutput;
  tasks: TaskItem[];
}

export interface GenerateSpecOptions {
  agent1Output?: Agent1Output;
  preferredStack?: string[];
}

// ─── Agent 4: DevSecOps, Quality & Automation ────────────────────────────────

/** A security policy enforced across the DevSecOps pipeline. */
export interface Agent4SecurityPolicy {
  /** Policy name (1–256 chars) */
  name: string;
  /** Policy description (1–256 chars) */
  description: string;
  /** How the policy is enforced (1–256 chars) */
  enforcement: string;
}

/** A single task item consumed by the DevSecOps pipeline. */
export interface Agent4TaskItem {
  /** Unique task identifier (1–64 chars) */
  id: string;
  /** Task title (1–256 chars) */
  title: string;
  /** Task description (1–1024 chars) */
  description: string;
  /** IDs of dependent tasks (each 1–64 chars, max 50) */
  dependencies: string[];
}

/** A package–license pair in the compliance report. */
export interface Agent4LicenseEntry {
  package: string;
  license: string;
}

/** Compliance report with license summary and regulatory flags. */
export interface Agent4ComplianceReport {
  /** At least one license entry */
  licenseSummary: Agent4LicenseEntry[];
  /** Regulatory flags (each non-empty) */
  regulatoryFlags: string[];
}

/** Composite input for Agent 4, combining outputs from Agents 1–3. */
export interface Agent4Input {
  /** Project name (1–128 chars) */
  projectName: string;
  /** Technology stack entries (each 1–64 chars, min 1, max 20) */
  stack: string[];
  /** Architecture pattern (constrained values) */
  architecturePattern: string;
  /** Security policies (min 1) */
  securityPolicies: Agent4SecurityPolicy[];
  /** Task list (min 1, max 200) */
  taskList: Agent4TaskItem[];
  /** Compliance report */
  complianceReport: Agent4ComplianceReport;
}

/** Hook scripts generated by Agent 4. */
export interface Agent4Hooks {
  /** validate-specs hook script (min 10 chars, starts with "#!/") */
  validateSpecs: string;
  /** scan-secrets hook script (min 10 chars, starts with "#!/") */
  scanSecrets: string;
}

/** Output artifacts generated by Agent 4. */
export interface Agent4Output {
  /** Multi-stage Dockerfile (min 20 chars, contains 2+ "FROM") */
  dockerfile: string;
  /** docker-compose.yml content (min 20 chars, contains "services") */
  dockerCompose: string;
  /** CI/CD pipeline YAML (min 20 chars, contains "jobs") */
  ciPipeline: string;
  /** Security hook scripts */
  hooks: Agent4Hooks;
}
